### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by mrkaban** [xvitaly/mhed#70]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/micro-hosts-editor-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80-hosts.html).

The project is interesting, so please don't abandon it!

Special thanks for the translation into Russian!

**Comment by xvitaly** [comment]
> Added a program to a Russian-language site about free software, here is the link.

Great. Thank you.

> The project is interesting, so please don't abandon it!

I'm going to publish version 1.0.0 next week with lots of changes.
